### ISSUE TITLE
About Positional Embeddings

### ISSUE THREAD

**Issue by RohollahHS** [bytedance/1d-tokenizer#56]
Hi,
Why is `pos_embed` also shuffled? Shouldn't it be the regular positional embedding like in ViT?
https://github.com/bytedance/1d-tokenizer/blob/6a8b33569d4feb68f59e7c96349a43e23d686e78/modeling/rar.py#L346

By shuffling `pos_embed`, it is treated exactly like `target_aware_pos_embed`. Please let me know if I am missing anything.
https://github.com/bytedance/1d-tokenizer/blob/6a8b33569d4feb68f59e7c96349a43e23d686e78/modeling/rar.py#L351

**Comment by cornettoyu** [comment]
Hi,

The original positional embedding is associated to the input tokens, and thus need to be shuffled as well (i.e., we are doing x = self.shuffle(x), pos_embed = self.shuffle(pos_embed), x = x + pos_emebd; alternatively you can just do x = x + pos_emebd, x = self.shuffle(x))

As for target_aware_pos_embed, as you can see in the code, they are shuffled and shifted, so that each token will see next token's pos embed as stated in the paper

**Comment by RohollahHS** [comment]
Thanks for the clarification. I understand it now. Could you please explain why the number of samples in `maskgitvq.jsonl` is about 12 million, while ImageNet has about 1 million samples?

**Comment by zhaoyanpeng** [comment]
cool idea! thanks for sharing. Are there any differences from [σ-GPTs: A New Approach to Autoregressive Models](https://arxiv.org/pdf/2404.09562)? It reads like an application of σ-GPTs to image generation, or am I missing something?

**Comment by cornettoyu** [comment]
> Thanks for the clarification. I understand it now. Could you please explain why the number of samples in `maskgitvq.jsonl` is about 12 million, while ImageNet has about 1 million samples?

Hi, this is because we use the 10-crops augmentation in pretokenization, which effectively multiplies the training samples by 10x and thus it shows 12M.

**Comment by RohollahHS** [comment]
Thanks.
